export const TAROT_IMAGES: Record<string, string> = {
  fool: "/tarot/01_fool.png",
  magician: "/tarot/02_magician.png",
  high_priestess: "/tarot/03_high_priestess.png",
  empress: "/tarot/04_empress.png",
  emperor: "/tarot/05_emperor.png",
  hierophant: "/tarot/06_hierophant.png",
  lovers: "/tarot/07_lovers.png",
  chariot: "/tarot/08_chariot.png",
  strength: "/tarot/09_strength.png",
  hermit: "/tarot/10_hermit.png",
  wheel_of_fortune: "/tarot/11_wheel_of_fortune.png",
  justice: "/tarot/12_justice.png",
  hanged_man: "/tarot/13_hanged_man.png",
  death: "/tarot/14_death.png",
  temperance: "/tarot/15_temperance.png",
  devil: "/tarot/16_devil.png",
  tower: "/tarot/17_tower.png",
  star: "/tarot/18_star.png",
  moon: "/tarot/19_moon.png",
  sun: "/tarot/20_sun.png",
  judgement: "/tarot/21_judgement.png",
  world: "/tarot/22_world.png",
};

